use_frameworks!

platform :ios, '11.0'

target 'TSUserNotifications_Example' do
  pod 'TSUserNotifications', :path => '../'

  target 'TSUserNotifications_Tests' do
    inherit! :search_paths

#    pod 'Quick', '~> 2.2.0'
#    pod 'Nimble', '~> 8.0.7'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 8.0.0'
  end
end
